server:
  port: 8080
  error:
      whitelabel:
        enabled: true
spring:
    resources:
       static-locations: classpath:/
    freemarker:
       template-loader-path: classpath:/templates/
       suffix: .html
       content-type: text/html
       charset: UTF-8
    datasource:
      url: jdbc:mysql://localhost:3307/test
      username: root
      password: liubing
      driver-class-name: com.mysql.jdbc.Driver







