spring:
  datasource:
    url: jdbc:mysql://111.231.55.110:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

